# Screw trajectory with cubic time scaling
# Good control gains - should track well
traj_type = 'SCREW_CUBIC'
duration_s = 5.0
actual_init_config = [0.1, -0.4, 0.4, 0.1, 0.1, 0.1]

[Ts_start]
SE3 = [
    [1.0, 0.0, 0.0, 0.4],
    [0.0, 1.0, 0.0, 0.2],
    [0.0, 0.0, 1.0, 0.4],
    [0.0, 0.0, 0.0, 1.0]
]

[Ts_end]
SE3 = [
    [0.0, 0.0, 1.0, 0.3],
    [0.0, 1.0, 0.0, -0.2],
    [-1.0, 0.0, 0.0, 0.5],
    [0.0, 0.0, 0.0, 1.0]
]
